version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:6.0
    container_name: vecino-mongodb-prod
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=vecino-marketplace
    networks:
      - vecino-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ['CMD', 'mongo', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching
  redis:
    image: redis:7.0-alpine
    container_name: vecino-redis-prod
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - vecino-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend service (production)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: vecino-backend-prod
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    networks:
      - vecino-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/health || exit 1']
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Frontend service (production)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: vecino-frontend-prod
    restart: always
    ports:
      - '80:80'
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - vecino-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  vecino-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
