branch-defaults:
  main:
    environment: vecino-marketplace-production
    group_suffix: null

global:
  application_name: vecino-marketplace-backend
  default_ec2_keyname: null
  default_platform: Node.js 18
  default_region: us-east-1
  include_git_submodules: true
  workspace_type: Application
